server:
  httplisten:  "0.0.0.0:80"

log:
  encoding:       "json"
  outputpaths:
    - "log/app.log"
    - "stdout"
  level:          "debug"
  initialfields:
    app:          "app"

db:
  reference:
    dialect:        "postgres"
    dsn:            "host=localhost port=5400 dbname=reference user=postgres password=1gjcnuhtc1! sslmode=disable"
    isautomigrate:  True
    log:
      loglevel:     4
  datasharding:
    isautomigrate:  True
    default:
      capacity:  1000000
      items:
        - dialect:        "postgres"
          dsn:            "host=localhost port=5400 dbname=data user=postgres password=1gjcnuhtc1! sslmode=disable"
          log:
            loglevel:     4

    BySysnames:
      AdvertisingCampaigns:
        capacity:  100000000
        entitytypes:
          - AdvertisingCampaign
          - Offer
        items:
          - dialect:        "postgres"
            dsn:            "host=localhost port=5400 dbname=data_rotated user=postgres password=1gjcnuhtc1! sslmode=disable"
            log:
              loglevel:     4

  redis:
    addrs:
      - "localhost:6379"
    login:    ""
    password: ""
    dbname:   0

auth:
  endpoint:     "http://localhost:8001"
  clientId:     "5e431f823a2bf338a213"
  clientSecret: "6b4a40bf3dd051f717900b75b2ca56c166007834"
  organization: "org"
  application:  "socbazar"
  SignInRedirectURL:  "http://localhost/api/account/signin"
  jwtsigningkey: "LxsKJywDL5O5PvgODZhBH12KE6k2yL8E"
  jwtexpiration: 72
  sessionlifetime: 96
  DefaultAccountSettings:
    Lang: "rus"

CacheLifeTime:  240